---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Disable sshd logging
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel QUIET'
  notify: restart sshd
